# Generated by Django 4.1.4 on 2023-05-04 10:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('anydesk', models.CharField(max_length=12)),
                ('session', models.CharField(max_length=150)),
                ('anypwd', models.CharField(max_length=150)),
                ('winpwd', models.CharField(max_length=150)),
                ('tel', models.CharField(max_length=50)),
                ('tel2', models.CharField(max_length=50)),
                ('note', models.TextField()),
                ('createdon', models.DateTimeField(default=datetime.datetime(2023, 5, 4, 11, 48, 3, 175078))),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.CharField(max_length=150)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
