# Generated by Django 4.1.4 on 2023-05-04 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='createdon',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 14, 18, 14, 769617)),
        ),
        migrations.AlterField(
            model_name='client',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='tel2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='updatedby',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
