# Generated by Django 3.2.18 on 2023-05-08 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_client_createdon_alter_client_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='createdon',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 11, 59, 14, 644841)),
        ),
    ]
