# Generated by Django 3.2.18 on 2023-05-08 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_client_createdon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='createdon',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 12, 49, 48, 232893)),
        ),
        migrations.AlterField(
            model_name='client',
            name='updatedon',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
