# Generated by Django 3.2.18 on 2023-05-08 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230508_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='createdon',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 12, 55, 38, 163613)),
        ),
        migrations.AlterField(
            model_name='client',
            name='updatedon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
