# Generated by Django 3.2.18 on 2023-05-08 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230508_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='createdon',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 13, 3, 36, 654856)),
        ),
        migrations.AlterField(
            model_name='client',
            name='updatedon',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
