# Generated by Django 4.2.1 on 2023-05-22 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_clientsimport_alter_client_createdon_delete_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='createdon',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 0, 58, 27, 585931)),
        ),
        migrations.AlterField(
            model_name='clientsimport',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 0, 58, 27, 585931)),
        ),
        migrations.AlterField(
            model_name='clientsimport',
            name='file',
            field=models.FileField(upload_to='Clients/'),
        ),
    ]
